-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 22:07:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema guilda_mercenários
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `guilda_mercenários` ;

-- -----------------------------------------------------
-- Schema guilda_mercenários
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guilda_mercenários` DEFAULT CHARACTER SET utf8 ;
USE `guilda_mercenários` ;

-- -----------------------------------------------------
-- Table `guilda_mercenários`.`filial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`filial` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`filial` (
  `Filial_id` INT NOT NULL AUTO_INCREMENT,
  `filial_Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Filial_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`raça`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`raça` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`raça` (
  `Raça_id` INT NOT NULL AUTO_INCREMENT,
  `Raça_Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Raça_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`ocupação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`ocupação` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`ocupação` (
  `Ocupação_id` INT NOT NULL AUTO_INCREMENT,
  `Ocupação_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Ocupação_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`posição`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`posição` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`posição` (
  `Posição_id` INT NOT NULL AUTO_INCREMENT,
  `Posição_Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Posição_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`tipo_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`tipo_documento` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`tipo_documento` (
  `Tipo_Documento_id` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Documento_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Tipo_Documento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`gênero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`gênero` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`gênero` (
  `Gênero_id` INT NOT NULL AUTO_INCREMENT,
  `Gênero_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Gênero_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`documento` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`documento` (
  `Documentos_id` INT NOT NULL AUTO_INCREMENT,
  `Posição_Posição_id` INT NOT NULL,
  `Tipo_Documento_Tipo_Documento_id` INT NOT NULL,
  `Gênero_Gênero_id` INT NOT NULL,
  `Raça_Raça_id` INT NOT NULL,
  `Documento_nome` VARCHAR(45) NULL,
  `Documento_data_nascimento` DATE NULL,
  PRIMARY KEY (`Documentos_id`),
  INDEX `fk_Documento_Posição1_idx` (`Posição_Posição_id` ASC) VISIBLE,
  INDEX `fk_Documento_Tipo_Documento1_idx` (`Tipo_Documento_Tipo_Documento_id` ASC) VISIBLE,
  INDEX `fk_Documento_Gênero1_idx` (`Gênero_Gênero_id` ASC) VISIBLE,
  INDEX `fk_Documento_Raça1_idx` (`Raça_Raça_id` ASC) VISIBLE,
  CONSTRAINT `fk_Documento_Posição1`
    FOREIGN KEY (`Posição_Posição_id`)
    REFERENCES `guilda_mercenários`.`posição` (`Posição_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Documento_Tipo_Documento1`
    FOREIGN KEY (`Tipo_Documento_Tipo_Documento_id`)
    REFERENCES `guilda_mercenários`.`tipo_documento` (`Tipo_Documento_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Documento_Gênero1`
    FOREIGN KEY (`Gênero_Gênero_id`)
    REFERENCES `guilda_mercenários`.`gênero` (`Gênero_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Documento_Raça1`
    FOREIGN KEY (`Raça_Raça_id`)
    REFERENCES `guilda_mercenários`.`raça` (`Raça_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`associado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`associado` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`associado` (
  `Associado_id` INT NOT NULL AUTO_INCREMENT,
  `Associado_altura` INT NULL,
  `Associado_peso` INT NULL,
  `Ocupação_Ocupação_id` INT NOT NULL,
  `Documento_Documentos_id` INT NOT NULL,
  PRIMARY KEY (`Associado_id`, `Documento_Documentos_id`),
  INDEX `fk_Associado_Ocupação1_idx` (`Ocupação_Ocupação_id` ASC) VISIBLE,
  INDEX `fk_Associado_Documento1_idx` (`Documento_Documentos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Associado_Ocupação1`
    FOREIGN KEY (`Ocupação_Ocupação_id`)
    REFERENCES `guilda_mercenários`.`ocupação` (`Ocupação_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Associado_Documento1`
    FOREIGN KEY (`Documento_Documentos_id`)
    REFERENCES `guilda_mercenários`.`documento` (`Documentos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`funcionário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`funcionário` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`funcionário` (
  `Funcionário_id` INT NOT NULL AUTO_INCREMENT,
  `Filial_Filial_id` INT NOT NULL,
  `Documento_Documentos_id` INT NOT NULL,
  PRIMARY KEY (`Funcionário_id`, `Filial_Filial_id`),
  INDEX `fk_Funcionário_Filial1_idx` (`Filial_Filial_id` ASC) VISIBLE,
  INDEX `fk_Funcionário_Documento1_idx` (`Documento_Documentos_id` ASC) VISIBLE,
  UNIQUE INDEX `Documento_Documentos_id_UNIQUE` (`Documento_Documentos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionário_Filial1`
    FOREIGN KEY (`Filial_Filial_id`)
    REFERENCES `guilda_mercenários`.`filial` (`Filial_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Funcionário_Documento1`
    FOREIGN KEY (`Documento_Documentos_id`)
    REFERENCES `guilda_mercenários`.`documento` (`Documentos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`tipo_expedição`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`tipo_expedição` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`tipo_expedição` (
  `Tipo_Expedição_id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Tipo_Expedição_risco` VARCHAR(45) NULL,
  PRIMARY KEY (`Tipo_Expedição_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`status` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`status` (
  `Status_id` INT NOT NULL AUTO_INCREMENT,
  `Status_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`tipo_território`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`tipo_território` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`tipo_território` (
  `Tipo_Território_id` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Território_Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Tipo_Território_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`criatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`criatura` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`criatura` (
  `Criatura_id` INT NOT NULL AUTO_INCREMENT,
  `Criatura_Especie` VARCHAR(45) NULL,
  `Criatura_Descrição` VARCHAR(45) NULL,
  `Raça_Raça_id` INT NOT NULL,
  PRIMARY KEY (`Criatura_id`),
  INDEX `fk_Criatura_Raça1_idx` (`Raça_Raça_id` ASC) VISIBLE,
  CONSTRAINT `fk_Criatura_Raça1`
    FOREIGN KEY (`Raça_Raça_id`)
    REFERENCES `guilda_mercenários`.`raça` (`Raça_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`soberano`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`soberano` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`soberano` (
  `Soberano_id` INT NOT NULL AUTO_INCREMENT,
  `Soberano_nome` VARCHAR(45) NULL,
  `Criatura_Criatura_id` INT NULL,
  `Documento_Documentos_id` INT NULL,
  PRIMARY KEY (`Soberano_id`),
  INDEX `fk_Soberano_Criatura1_idx` (`Criatura_Criatura_id` ASC) VISIBLE,
  INDEX `fk_Soberano_Documento1_idx` (`Documento_Documentos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Soberano_Criatura1`
    FOREIGN KEY (`Criatura_Criatura_id`)
    REFERENCES `guilda_mercenários`.`criatura` (`Criatura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Soberano_Documento1`
    FOREIGN KEY (`Documento_Documentos_id`)
    REFERENCES `guilda_mercenários`.`documento` (`Documentos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`território`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`território` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`território` (
  `Território_id` INT NOT NULL AUTO_INCREMENT,
  `Território_Nome` VARCHAR(45) NULL,
  `Tipo_Território_Tipo_Território_id1` INT NOT NULL,
  `soberano_Soberano_id` INT NOT NULL,
  PRIMARY KEY (`Território_id`),
  INDEX `fk_Território_Tipo_Território1_idx` (`Tipo_Território_Tipo_Território_id1` ASC) VISIBLE,
  INDEX `fk_território_soberano1_idx` (`soberano_Soberano_id` ASC) VISIBLE,
  CONSTRAINT `fk_Território_Tipo_Território1`
    FOREIGN KEY (`Tipo_Território_Tipo_Território_id1`)
    REFERENCES `guilda_mercenários`.`tipo_território` (`Tipo_Território_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_território_soberano1`
    FOREIGN KEY (`soberano_Soberano_id`)
    REFERENCES `guilda_mercenários`.`soberano` (`Soberano_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`encomenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`encomenda` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`encomenda` (
  `Encomenda_id` INT NOT NULL AUTO_INCREMENT,
  `Associado_Associado_id` INT NOT NULL,
  `Funcionário_Funcionário_id` INT NOT NULL,
  `Tipo_Expedição_Tipo_Expedição_id` INT NOT NULL,
  `Encomenda_Data_Registro` DATE NULL,
  `Encomenda_Num_Min_mercenários` INT NULL,
  `Encomenda_preco` FLOAT NULL,
  `Encomenda_descrição` VARCHAR(100) NULL,
  `Encomenda_data_limite` DATE NULL,
  `Encomenda_prev_risco` INT NULL,
  `Encomenda_taxa_extra` TINYINT NULL,
  `Status_Status_id` INT NOT NULL,
  `território_Território_id` INT NOT NULL,
  PRIMARY KEY (`Encomenda_id`, `Associado_Associado_id`, `Funcionário_Funcionário_id`),
  INDEX `fk_Encomenda_Associado1_idx` (`Associado_Associado_id` ASC) VISIBLE,
  INDEX `fk_Encomenda_Funcionário1_idx` (`Funcionário_Funcionário_id` ASC) VISIBLE,
  INDEX `fk_Encomenda_Tipo_Expedição1_idx` (`Tipo_Expedição_Tipo_Expedição_id` ASC) VISIBLE,
  INDEX `fk_Encomenda_Status1_idx` (`Status_Status_id` ASC) VISIBLE,
  INDEX `fk_encomenda_território1_idx` (`território_Território_id` ASC) VISIBLE,
  CONSTRAINT `fk_Encomenda_Associado1`
    FOREIGN KEY (`Associado_Associado_id`)
    REFERENCES `guilda_mercenários`.`associado` (`Associado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Encomenda_Funcionário1`
    FOREIGN KEY (`Funcionário_Funcionário_id`)
    REFERENCES `guilda_mercenários`.`funcionário` (`Funcionário_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Encomenda_Tipo_Expedição1`
    FOREIGN KEY (`Tipo_Expedição_Tipo_Expedição_id`)
    REFERENCES `guilda_mercenários`.`tipo_expedição` (`Tipo_Expedição_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Encomenda_Status1`
    FOREIGN KEY (`Status_Status_id`)
    REFERENCES `guilda_mercenários`.`status` (`Status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_encomenda_território1`
    FOREIGN KEY (`território_Território_id`)
    REFERENCES `guilda_mercenários`.`território` (`Território_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`expólio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`expólio` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`expólio` (
  `Expólios_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Expólios_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`expedição`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`expedição` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`expedição` (
  `Expedição_id` INT NOT NULL AUTO_INCREMENT,
  `Encomenda_Encomenda_id` INT NOT NULL,
  `Encomenda_Associado_Associado_id` INT NOT NULL,
  `Encomenda_Funcionário_Funcionário_id` INT NOT NULL,
  `Expedição_data_conclusão` DATE NULL,
  `Expólios_Expólios_id` INT NULL,
  `Status_Status_id` INT NOT NULL,
  PRIMARY KEY (`Expedição_id`, `Encomenda_Encomenda_id`, `Encomenda_Associado_Associado_id`, `Encomenda_Funcionário_Funcionário_id`),
  INDEX `fk_Expedição_Encomenda1_idx` (`Encomenda_Encomenda_id` ASC, `Encomenda_Associado_Associado_id` ASC, `Encomenda_Funcionário_Funcionário_id` ASC) VISIBLE,
  INDEX `fk_Expedição_Expólios1_idx` (`Expólios_Expólios_id` ASC) VISIBLE,
  INDEX `fk_Expedição_Status1_idx` (`Status_Status_id` ASC) VISIBLE,
  CONSTRAINT `fk_Expedição_Encomenda1`
    FOREIGN KEY (`Encomenda_Encomenda_id` , `Encomenda_Associado_Associado_id` , `Encomenda_Funcionário_Funcionário_id`)
    REFERENCES `guilda_mercenários`.`encomenda` (`Encomenda_id` , `Associado_Associado_id` , `Funcionário_Funcionário_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Expedição_Expólios1`
    FOREIGN KEY (`Expólios_Expólios_id`)
    REFERENCES `guilda_mercenários`.`expólio` (`Expólios_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Expedição_Status1`
    FOREIGN KEY (`Status_Status_id`)
    REFERENCES `guilda_mercenários`.`status` (`Status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`filial_has_Associado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`filial_has_Associado` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`filial_has_Associado` (
  `Filial_Filial_id` INT NOT NULL,
  `Associado_Associado_id` INT NOT NULL,
  PRIMARY KEY (`Filial_Filial_id`, `Associado_Associado_id`),
  INDEX `fk_Filial_has_Associado_Associado1_idx` (`Associado_Associado_id` ASC) VISIBLE,
  INDEX `fk_Filial_has_Associado_Filial_idx` (`Filial_Filial_id` ASC) VISIBLE,
  CONSTRAINT `fk_Filial_has_Associado_Filial`
    FOREIGN KEY (`Filial_Filial_id`)
    REFERENCES `guilda_mercenários`.`filial` (`Filial_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Filial_has_Associado_Associado1`
    FOREIGN KEY (`Associado_Associado_id`)
    REFERENCES `guilda_mercenários`.`associado` (`Associado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`disponibilidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`disponibilidade` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`disponibilidade` (
  `Disponibilidade_id` INT NOT NULL AUTO_INCREMENT,
  `Disponibilidade_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Disponibilidade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`mercenário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`mercenário` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`mercenário` (
  `Mercenários_id` INT NOT NULL AUTO_INCREMENT,
  `Documento_Documentos_id` INT NOT NULL,
  `Mercenário_data_efetivação` VARCHAR(45) NULL,
  `Disponibilidade_Disponibilidade_id` INT NOT NULL,
  PRIMARY KEY (`Mercenários_id`),
  INDEX `fk_Mercenário_Documento1_idx` (`Documento_Documentos_id` ASC) VISIBLE,
  INDEX `fk_Mercenário_Disponibilidade1_idx` (`Disponibilidade_Disponibilidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mercenário_Disponibilidade1`
    FOREIGN KEY (`Disponibilidade_Disponibilidade_id`)
    REFERENCES `guilda_mercenários`.`disponibilidade` (`Disponibilidade_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mercenário_Documento1`
    FOREIGN KEY (`Documento_Documentos_id`)
    REFERENCES `guilda_mercenários`.`documento` (`Documentos_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`filial_has_Mercenários`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`filial_has_Mercenários` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`filial_has_Mercenários` (
  `Filial_Filial_id` INT NOT NULL,
  `Mercenários_Mercenários_id` INT NOT NULL,
  PRIMARY KEY (`Filial_Filial_id`, `Mercenários_Mercenários_id`),
  INDEX `fk_Filial_has_Mercenários_Mercenários1_idx` (`Mercenários_Mercenários_id` ASC) VISIBLE,
  INDEX `fk_Filial_has_Mercenários_Filial1_idx` (`Filial_Filial_id` ASC) VISIBLE,
  CONSTRAINT `fk_Filial_has_Mercenários_Filial1`
    FOREIGN KEY (`Filial_Filial_id`)
    REFERENCES `guilda_mercenários`.`filial` (`Filial_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Filial_has_Mercenários_Mercenários1`
    FOREIGN KEY (`Mercenários_Mercenários_id`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`encomenda_has_mercenários_requisitados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`encomenda_has_mercenários_requisitados` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`encomenda_has_mercenários_requisitados` (
  `Encomenda_Encomenda_id` INT NOT NULL,
  `Encomenda_Associado_Associado_id` INT NOT NULL,
  `Encomenda_Funcionário_Funcionário_id` INT NOT NULL,
  `Mercenários_Mercenários_id` INT NOT NULL,
  PRIMARY KEY (`Encomenda_Encomenda_id`, `Encomenda_Associado_Associado_id`, `Encomenda_Funcionário_Funcionário_id`, `Mercenários_Mercenários_id`),
  INDEX `fk_Encomenda_has_Mercenários_Mercenários1_idx` (`Mercenários_Mercenários_id` ASC) VISIBLE,
  INDEX `fk_Encomenda_has_Mercenários_Encomenda1_idx` (`Encomenda_Encomenda_id` ASC, `Encomenda_Associado_Associado_id` ASC, `Encomenda_Funcionário_Funcionário_id` ASC) VISIBLE,
  CONSTRAINT `fk_Encomenda_has_Mercenários_Encomenda1`
    FOREIGN KEY (`Encomenda_Encomenda_id` , `Encomenda_Associado_Associado_id` , `Encomenda_Funcionário_Funcionário_id`)
    REFERENCES `guilda_mercenários`.`encomenda` (`Encomenda_id` , `Associado_Associado_id` , `Funcionário_Funcionário_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Encomenda_has_Mercenários_Mercenários1`
    FOREIGN KEY (`Mercenários_Mercenários_id`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`tipo_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`tipo_pagamento` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`tipo_pagamento` (
  `Tipo_Pagamento_id` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Pagamento_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Tipo_Pagamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`pagamento` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`pagamento` (
  `Pagamento_id` INT NOT NULL AUTO_INCREMENT,
  `Pagamento_parcelas` INT NULL,
  `Tipo_Pagamento_Tipo_Pagamento_id1` INT NOT NULL,
  `encomenda_Encomenda_id` INT NOT NULL,
  `encomenda_Associado_Associado_id` INT NOT NULL,
  `encomenda_Funcionário_Funcionário_id` INT NOT NULL,
  PRIMARY KEY (`Pagamento_id`),
  INDEX `fk_Pagamento_Tipo_Pagamento1_idx` (`Tipo_Pagamento_Tipo_Pagamento_id1` ASC) VISIBLE,
  INDEX `fk_pagamento_encomenda1_idx` (`encomenda_Encomenda_id` ASC, `encomenda_Associado_Associado_id` ASC, `encomenda_Funcionário_Funcionário_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento_Tipo_Pagamento1`
    FOREIGN KEY (`Tipo_Pagamento_Tipo_Pagamento_id1`)
    REFERENCES `guilda_mercenários`.`tipo_pagamento` (`Tipo_Pagamento_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pagamento_encomenda1`
    FOREIGN KEY (`encomenda_Encomenda_id` , `encomenda_Associado_Associado_id` , `encomenda_Funcionário_Funcionário_id`)
    REFERENCES `guilda_mercenários`.`encomenda` (`Encomenda_id` , `Associado_Associado_id` , `Funcionário_Funcionário_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`estação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`estação` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`estação` (
  `id_Estação` INT NOT NULL AUTO_INCREMENT,
  `Estação_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Estação`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`território_has_risco_estação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`território_has_risco_estação` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`território_has_risco_estação` (
  `Território_Território_id` INT NOT NULL,
  `Território_has_Risco_Estação_Risco` INT NULL,
  `estação_id_Estação` INT NOT NULL,
  PRIMARY KEY (`Território_Território_id`, `estação_id_Estação`),
  INDEX `fk_Território_has_Risco_Estação_Território1_idx` (`Território_Território_id` ASC) VISIBLE,
  INDEX `fk_território_has_risco_estação_estação1_idx` (`estação_id_Estação` ASC) VISIBLE,
  CONSTRAINT `fk_Território_has_Risco_Estação_Território1`
    FOREIGN KEY (`Território_Território_id`)
    REFERENCES `guilda_mercenários`.`território` (`Território_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_território_has_risco_estação_estação1`
    FOREIGN KEY (`estação_id_Estação`)
    REFERENCES `guilda_mercenários`.`estação` (`id_Estação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`fraqueza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`fraqueza` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`fraqueza` (
  `Fraqueza_id` INT NOT NULL AUTO_INCREMENT,
  `Fraqueza_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Fraqueza_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`criatura_has_fraqueza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`criatura_has_fraqueza` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`criatura_has_fraqueza` (
  `Criatura_Criatura_id` INT NOT NULL,
  `Fraqueza_Fraqueza_id` INT NOT NULL,
  PRIMARY KEY (`Criatura_Criatura_id`, `Fraqueza_Fraqueza_id`),
  INDEX `fk_Criatura_has_Fraqueza_Fraqueza1_idx` (`Fraqueza_Fraqueza_id` ASC) VISIBLE,
  INDEX `fk_Criatura_has_Fraqueza_Criatura1_idx` (`Criatura_Criatura_id` ASC) VISIBLE,
  CONSTRAINT `fk_Criatura_has_Fraqueza_Criatura1`
    FOREIGN KEY (`Criatura_Criatura_id`)
    REFERENCES `guilda_mercenários`.`criatura` (`Criatura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Criatura_has_Fraqueza_Fraqueza1`
    FOREIGN KEY (`Fraqueza_Fraqueza_id`)
    REFERENCES `guilda_mercenários`.`fraqueza` (`Fraqueza_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`criatura_has_risco_estação`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`criatura_has_risco_estação` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`criatura_has_risco_estação` (
  `Criatura_Criatura_id` INT NOT NULL,
  `estação_id_Estação` INT NOT NULL,
  `criatura_has_risco_estação_Risco` INT NULL,
  PRIMARY KEY (`Criatura_Criatura_id`, `estação_id_Estação`),
  INDEX `fk_Criatura_has_Estação_Criatura1_idx` (`Criatura_Criatura_id` ASC) VISIBLE,
  INDEX `fk_criatura_has_risco_estação_estação1_idx` (`estação_id_Estação` ASC) VISIBLE,
  CONSTRAINT `fk_Criatura_has_Estação_Criatura1`
    FOREIGN KEY (`Criatura_Criatura_id`)
    REFERENCES `guilda_mercenários`.`criatura` (`Criatura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_criatura_has_risco_estação_estação1`
    FOREIGN KEY (`estação_id_Estação`)
    REFERENCES `guilda_mercenários`.`estação` (`id_Estação`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`território_has_criatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`território_has_criatura` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`território_has_criatura` (
  `Território_Território_id` INT NOT NULL,
  `Criatura_Criatura_id` INT NOT NULL,
  PRIMARY KEY (`Território_Território_id`, `Criatura_Criatura_id`),
  INDEX `fk_Território_has_Criatura_Criatura1_idx` (`Criatura_Criatura_id` ASC) VISIBLE,
  INDEX `fk_Território_has_Criatura_Território1_idx` (`Território_Território_id` ASC) VISIBLE,
  CONSTRAINT `fk_Território_has_Criatura_Território1`
    FOREIGN KEY (`Território_Território_id`)
    REFERENCES `guilda_mercenários`.`território` (`Território_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Território_has_Criatura_Criatura1`
    FOREIGN KEY (`Criatura_Criatura_id`)
    REFERENCES `guilda_mercenários`.`criatura` (`Criatura_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`parcela`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`parcela` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`parcela` (
  `Parcela_id` INT NOT NULL AUTO_INCREMENT,
  `Pagamento_Pagamento_id` INT NOT NULL,
  PRIMARY KEY (`Parcela_id`, `Pagamento_Pagamento_id`),
  INDEX `fk_Parcela_Pagamento1_idx` (`Pagamento_Pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_Parcela_Pagamento1`
    FOREIGN KEY (`Pagamento_Pagamento_id`)
    REFERENCES `guilda_mercenários`.`pagamento` (`Pagamento_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`equipe` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`equipe` (
  `Equipe_id` INT NOT NULL AUTO_INCREMENT,
  `Expedição_Expedição_id` INT NOT NULL,
  `Expedição_Encomenda_Encomenda_id` INT NOT NULL,
  `Expedição_Encomenda_Associado_Associado_id` INT NOT NULL,
  `Expedição_Encomenda_Funcionário_Funcionário_id` INT NOT NULL,
  PRIMARY KEY (`Equipe_id`),
  INDEX `fk_Equipe_Expedição1_idx` (`Expedição_Expedição_id` ASC, `Expedição_Encomenda_Encomenda_id` ASC, `Expedição_Encomenda_Associado_Associado_id` ASC, `Expedição_Encomenda_Funcionário_Funcionário_id` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_Expedição1`
    FOREIGN KEY (`Expedição_Expedição_id` , `Expedição_Encomenda_Encomenda_id` , `Expedição_Encomenda_Associado_Associado_id` , `Expedição_Encomenda_Funcionário_Funcionário_id`)
    REFERENCES `guilda_mercenários`.`expedição` (`Expedição_id` , `Encomenda_Encomenda_id` , `Encomenda_Associado_Associado_id` , `Encomenda_Funcionário_Funcionário_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`equipe_has_mercenário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`equipe_has_mercenário` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`equipe_has_mercenário` (
  `Equipe_Equipe_id` INT NOT NULL,
  `Mercenário_Mercenários_id` INT NOT NULL,
  `Status_Status_id` INT NULL,
  PRIMARY KEY (`Equipe_Equipe_id`, `Mercenário_Mercenários_id`),
  INDEX `fk_Equipe_has_Mercenário_Mercenário1_idx` (`Mercenário_Mercenários_id` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Mercenário_Equipe1_idx` (`Equipe_Equipe_id` ASC) VISIBLE,
  INDEX `fk_Equipe_has_Mercenário_Status1_idx` (`Status_Status_id` ASC) VISIBLE,
  CONSTRAINT `fk_Equipe_has_Mercenário_Equipe1`
    FOREIGN KEY (`Equipe_Equipe_id`)
    REFERENCES `guilda_mercenários`.`equipe` (`Equipe_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Equipe_has_Mercenário_Mercenário1`
    FOREIGN KEY (`Mercenário_Mercenários_id`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Equipe_has_Mercenário_Status1`
    FOREIGN KEY (`Status_Status_id`)
    REFERENCES `guilda_mercenários`.`status` (`Status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`item` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`item` (
  `Item_id` INT NOT NULL AUTO_INCREMENT,
  `Expólio_Expólios_id` INT NOT NULL,
  `Item_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Item_id`),
  INDEX `fk_Item_Expólio1_idx` (`Expólio_Expólios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Item_Expólio1`
    FOREIGN KEY (`Expólio_Expólios_id`)
    REFERENCES `guilda_mercenários`.`expólio` (`Expólios_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`gravidade_infracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`gravidade_infracao` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`gravidade_infracao` (
  `idgravidade_infracao` INT NOT NULL AUTO_INCREMENT,
  `gravidade_infracao_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idgravidade_infracao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`infração`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`infração` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`infração` (
  `Infração_id` INT NOT NULL AUTO_INCREMENT,
  `Infração_descrição` VARCHAR(45) NULL,
  `gravidade_infracao_idgravidade_infracao` INT NOT NULL,
  PRIMARY KEY (`Infração_id`),
  INDEX `fk_infração_gravidade_infracao1_idx` (`gravidade_infracao_idgravidade_infracao` ASC) VISIBLE,
  CONSTRAINT `fk_infração_gravidade_infracao1`
    FOREIGN KEY (`gravidade_infracao_idgravidade_infracao`)
    REFERENCES `guilda_mercenários`.`gravidade_infracao` (`idgravidade_infracao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`mercenário_has_infração`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`mercenário_has_infração` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`mercenário_has_infração` (
  `Mercenário_Mercenários_id` INT NOT NULL,
  `Infração_Infração_id` INT NOT NULL,
  `Mercenário_has_Infração_data` VARCHAR(45) NULL,
  `Mercenário_has_Infração_descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`Mercenário_Mercenários_id`, `Infração_Infração_id`),
  INDEX `fk_Mercenário_has_Infração_Infração1_idx` (`Infração_Infração_id` ASC) VISIBLE,
  INDEX `fk_Mercenário_has_Infração_Mercenário1_idx` (`Mercenário_Mercenários_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mercenário_has_Infração_Mercenário1`
    FOREIGN KEY (`Mercenário_Mercenários_id`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mercenário_has_Infração_Infração1`
    FOREIGN KEY (`Infração_Infração_id`)
    REFERENCES `guilda_mercenários`.`infração` (`Infração_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`especialidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`especialidade` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`especialidade` (
  `Especialidade_id` INT NOT NULL AUTO_INCREMENT,
  `Especialidade_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Especialidade_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`mercenário_has_especialidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`mercenário_has_especialidade` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`mercenário_has_especialidade` (
  `Mercenário_Mercenários_id` INT NOT NULL,
  `Especialidade_Especialidade_id` INT NOT NULL,
  `Mercenário_has_Especialidade_proficiência` VARCHAR(45) NULL,
  PRIMARY KEY (`Mercenário_Mercenários_id`, `Especialidade_Especialidade_id`),
  INDEX `fk_Mercenário_has_Especialidade_Especialidade1_idx` (`Especialidade_Especialidade_id` ASC) VISIBLE,
  INDEX `fk_Mercenário_has_Especialidade_Mercenário1_idx` (`Mercenário_Mercenários_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mercenário_has_Especialidade_Mercenário1`
    FOREIGN KEY (`Mercenário_Mercenários_id`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mercenário_has_Especialidade_Especialidade1`
    FOREIGN KEY (`Especialidade_Especialidade_id`)
    REFERENCES `guilda_mercenários`.`especialidade` (`Especialidade_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`mercenário_has_mercenário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`mercenário_has_mercenário` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`mercenário_has_mercenário` (
  `Mercenário_Mercenários_id` INT NOT NULL,
  `Mercenário_Mercenários_id1` INT NOT NULL,
  PRIMARY KEY (`Mercenário_Mercenários_id`, `Mercenário_Mercenários_id1`),
  INDEX `fk_Mercenário_has_Mercenário_Mercenário2_idx` (`Mercenário_Mercenários_id1` ASC) VISIBLE,
  INDEX `fk_Mercenário_has_Mercenário_Mercenário1_idx` (`Mercenário_Mercenários_id` ASC) VISIBLE,
  CONSTRAINT `fk_Mercenário_has_Mercenário_Mercenário1`
    FOREIGN KEY (`Mercenário_Mercenários_id`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Mercenário_has_Mercenário_Mercenário2`
    FOREIGN KEY (`Mercenário_Mercenários_id1`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`vilarejo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`vilarejo` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`vilarejo` (
  `idVilarejo` INT NOT NULL AUTO_INCREMENT,
  `Vilarejo_Nome` VARCHAR(45) NULL,
  `território_Território_id` INT NOT NULL,
  PRIMARY KEY (`idVilarejo`),
  INDEX `fk_vilarejo_território1_idx` (`território_Território_id` ASC) VISIBLE,
  CONSTRAINT `fk_vilarejo_território1`
    FOREIGN KEY (`território_Território_id`)
    REFERENCES `guilda_mercenários`.`território` (`Território_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`endereço` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`endereço` (
  `idEndereço` INT NOT NULL AUTO_INCREMENT,
  `Vilarejo_idVilarejo` INT NOT NULL,
  `Endereço_Rua` VARCHAR(45) NULL,
  `Endereco_Casa` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereço`),
  INDEX `fk_Endereço_Vilarejo1_idx` (`Vilarejo_idVilarejo` ASC) VISIBLE,
  CONSTRAINT `fk_Endereço_Vilarejo1`
    FOREIGN KEY (`Vilarejo_idVilarejo`)
    REFERENCES `guilda_mercenários`.`vilarejo` (`idVilarejo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`associado_has_endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`associado_has_endereço` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`associado_has_endereço` (
  `associado_Associado_id` INT NOT NULL,
  `associado_Documento_Documentos_id` INT NOT NULL,
  `endereço_idEndereço` INT NOT NULL,
  PRIMARY KEY (`associado_Associado_id`, `associado_Documento_Documentos_id`, `endereço_idEndereço`),
  INDEX `fk_associado_has_endereço_endereço1_idx` (`endereço_idEndereço` ASC) VISIBLE,
  INDEX `fk_associado_has_endereço_associado1_idx` (`associado_Associado_id` ASC, `associado_Documento_Documentos_id` ASC) VISIBLE,
  CONSTRAINT `fk_associado_has_endereço_associado1`
    FOREIGN KEY (`associado_Associado_id` , `associado_Documento_Documentos_id`)
    REFERENCES `guilda_mercenários`.`associado` (`Associado_id` , `Documento_Documentos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_associado_has_endereço_endereço1`
    FOREIGN KEY (`endereço_idEndereço`)
    REFERENCES `guilda_mercenários`.`endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `guilda_mercenários`.`mercenário_has_endereço`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `guilda_mercenários`.`mercenário_has_endereço` ;

CREATE TABLE IF NOT EXISTS `guilda_mercenários`.`mercenário_has_endereço` (
  `mercenário_Mercenários_id` INT NOT NULL,
  `endereço_idEndereço` INT NOT NULL,
  PRIMARY KEY (`mercenário_Mercenários_id`, `endereço_idEndereço`),
  INDEX `fk_mercenário_has_endereço_endereço1_idx` (`endereço_idEndereço` ASC) VISIBLE,
  INDEX `fk_mercenário_has_endereço_mercenário1_idx` (`mercenário_Mercenários_id` ASC) VISIBLE,
  CONSTRAINT `fk_mercenário_has_endereço_mercenário1`
    FOREIGN KEY (`mercenário_Mercenários_id`)
    REFERENCES `guilda_mercenários`.`mercenário` (`Mercenários_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mercenário_has_endereço_endereço1`
    FOREIGN KEY (`endereço_idEndereço`)
    REFERENCES `guilda_mercenários`.`endereço` (`idEndereço`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
